language: go

go:
  - 1.6

before_install:
  - pip install -r requirements.txt

install:
  - "python --version"
  - "python2.7 -- version"
  - "pip --version"
  - "trial --version"

script:
  - "go build -o test"
  - "go test"
  - "./test"
