language: go
sudo: required

go:
  - 1.6

before_install:
  - pyenv global 2.7.10
  - sudo pip install -r requirements.txt

install:
  - "python --version"
  - "pip --version"
  - "trial --version"

script:
  - "go build -o test"
  - "go test"
  - "./test"
